adminUser:
  organization: "${organisation}"
  bucket: "${bucket}"
  # Should not be applied on first run...
  existingSecret: "influxdb2-auth"

persistence:
  storageClass: "nfs-client"

ingress:
  enabled: true
  ingressClassName: nginx
  # influxdb2 chart currently does not work correctly on just
  # ingressClassName. Set the annotation as well to be sure the
  # endpoint gets set properly.
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hostname: influx.${domain}

