ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: loki.choclab.net
      paths:
        - "/"
persistence:
  enabled: true
  storageClassName: "nfs-client"

