ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: "loki.${domain}"
      paths:
        - "/"
persistence:
  enabled: true
  storageClassName: "nfs-client"

