---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-db
  namespace: monitoring
type: Opaque
data:
  GF_DATABASE_USER: ""
  GF_DATABASE_PASSWORD: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
data:
  username: ""
  password: ""


