global:
  datacenter: choclab
  enablePodSecurityPolicies: true
  gossipEncryption:
    secretName: consul
    secretKey: gossip
  tls:
    enabled: true
    enableAutoEncrypt: true
    serverAdditionalDNSSANs:
      - consul.choclab.net
    caCert:
      secretName: consul
      secretKey: cacert
    caKey:
      secretName: consul
      secretKey: cakey
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
server:
  storageClass: nfs-client
ui:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: "nginx"
    pathType: Prefix
    hosts:
      - host: consul.choclab.net
        paths:
          - "/"
    tls: []
    annotations: null
  metrics:
    enabled: "-"
    provider: "prometheus"
    baseURL: http://prometheus-server
