global:
  tlsDisable: false

server:

  ingress:
    enabled: true
    labels: {}
      # traffic: external
    annotations:
      # kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: "nginx"

    pathType: Prefix
    activeService: true
    hosts:
      - host: vault.${domain}
        paths:
          - "/"
    tls:
      - secretName: ${datacentre}-vault-cert
        hosts:
          - vault.${domain}


  extraEnvironmentVars:
    VAULT_CACERT: /etc/ssl/consul/cacert

  extraSecretEnvironmentVars:
    - envName: CONSUL_HTTP_TOKEN
      secretName: vault-consul-acl-token
      secretKey: token


  volumes:
    - name: consul-consul-server-cert
      secret:
        secretName: consul-consul-server-cert
    - name: consul
      secret:
        secretName: consul
    - name: ${datacentre}-vault-cert
      secret:
        secretName: ${datacentre}-vault-cert

  volumeMounts:
     - mountPath: /etc/ssl/consul-cert
       name: consul-consul-server-cert
       readOnly: true
     - mountPath: /etc/ssl/consul
       name: consul
       readOnly: true
     - mountPath: /etc/ssl/${datacentre}-vault-cert
       name: ${datacentre}-vault-cert
       readOnly: true

  # Enables network policy for server pods
  networkPolicy:
    enabled: false
    egress: []
    # egress:
    # - to:
    #   - ipBlock:
    #       cidr: 10.0.0.0/24
    #   ports:
    #   - protocol: TCP
    #     port: 443

  dataStorage:
    storageClass: nfs-client
  auditStorage:
    enabled: true
    storageClass: nfs-client

  ha:
    enabled: true
    replicas: 3
    apiAddr: "https://127.0.0.1:8200"
    raft:
      enabled: false
    config: |
      ui = true
      api_addr = "https://vault.${domain}"
      disable_performance_standby = "false"

      listener "tcp" {
        tls_disable = "false"
        tls_cert_file = "/etc/ssl/${datacentre}-vault-cert/tls.crt"
        tls_key_file = "/etc/ssl/${datacentre}-vault-cert/tls.key"
        address = "POD_IP:8200"
        cluster_address = "POD_IP:8201"
      }

      listener "tcp" {
        tls_disable = "false"
        address = "127.0.0.1:8200"
        cluster_address = "127.0.0.1:8201"
        tls_cert_file = "/etc/ssl/consul-cert/tls.crt"
        tls_key_file = "/etc/ssl/consul-cert/tls.key"
      }

      storage "consul" {
        path = "vault"
        address = "consul-consul-server:8501"
        scheme = "https"
        tls_cert_file = "/etc/ssl/consul-cert/tls.crt"
        tls_key_file = "/etc/ssl/consul-cert/tls.key"
        tls_ca_file = "/etc/ssl/consul/cacert"
        tls_skip_verify = "true"
      }

      service_registration "kubernetes" {}
ui:
  enabled: true
