autoscaling:
  enabled:  true
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 60

image:
  tag: 8.3.3

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.choclab.net

admin:
  existingSecret: "grafana-admin"
  userKey: username
  passwordKey: password

envFromSecret: "grafana-db"

grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net

  database:
    type: "mysql"
    host: "nebula.choclab.net:3306"
    name: "grafana"

