controller:
  image:
    allowPrivilegeEscalation: false

  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
      tcp:
        8080: 32808

tcp:
  8201: "vault/vault-active:8201"

